Repository tdameros/42-transcendence, pull requests merged in 2024-03, with the labels that each got.

#322 Send the first matches to game creator when the tournament starts
  .github/workflows/pong-server.yaml
  common/src/internal_requests.py
  common/src/jwt_managers.py
  front/app/src/js/components/game/Scene/Match.js
  pong_server/dev_game_creator.sh
  pong_server/dev_game_server.sh
  pong_server/src/game_server/ConnectError.py
  pong_server/src/game_server/EventHandler.py
  pong_server/src/game_server/Game/GameManager.py
  pong_server/src/game_server/Game/Match.py
  pong_server/src/game_server/PostSender/_TournamentAPI.py
  pong_server/src/game_server/PostSender/_UserStatsAPI.py
  pong_server/src/game_server/Server.py
  pong_server/src/shared_code/settings.py
  pong_server/test_game_creator.sh
  tournament/src/api/tests/test_tournament.py
  tournament/src/api/views/manage_tournament_views.py
Labels: enhancement

#336 fix match against yourself
  matchmaking/src/error_message.py
  matchmaking/src/matchmaking.py
  matchmaking/src/server.py
Labels: bug

#323 generate random key for access jwt (and more)
  .env
  .env_example
  .github/workflows/matchmaking.yaml
  .github/workflows/notification.yaml
  .github/workflows/pong-server.yaml
  .github/workflows/tournament.yaml
  .github/workflows/user_management.yaml
  .github/workflows/user_stats.yaml
  .gitignore
  common/src/generate_env.py
  common/src/generate_pair_of_keys.py
  common/src/settings.py
  notification/docker/docker-compose.yaml
  notification/src/notification/settings.py
  pong_server/docker/run.sh
  pong_server/src/game_creator/game_creator/settings.py
  tournament/docker/docker-compose.yaml
  tournament/src/tournament/settings.py
  user_management/docker/docker-compose.yaml
  user_management/src/user/migrations/0001_initial.py
  user_management/src/user/migrations/0002_user_email_user_password.py
  user_management/src/user/migrations/0003_user_forgotpasswordcode_and_more.py
  user_management/src/user/migrations/0004_pendingoauth.py
  user_management/src/user/migrations/0005_pendingoauth_created_at.py
  user_management/src/user/migrations/0006_user_avatar_alter_user_password.py
  user_management/src/user/migrations/0007_pendingoauth_source_alter_user_forgotpasswordcode.py
  user_management/src/user/migrations/0008_remove_user_elo.py
  user_management/src/user/migrations/0008_user_has_2fa_user_totp_config_url_user_totp_secret.py
  user_management/src/user/migrations/0009_merge_20240205_1342.py
  user_management/src/user/migrations/0010_friend.py
  user_management/src/user/migrations/0011_user_account_deleted_alter_pendingoauth_hashed_state.py
  user_management/src/user/migrations/0012_user_emailverificationtoken_and_more.py
  user_management/src/user/migrations/0012_user_last_activity_alter_user_password.py
  user_management/src/user/migrations/0013_user_last_login.py
  user_management/src/user/migrations/0014_merge_20240227_1449.py
  user_management/src/user/test_friends.py
  user_management/src/user_management/.env-example
  user_management/src/user_management/settings.py
  user_stats/docker/docker-compose.yaml
  user_stats/docker/requirements.txt
  user_stats/src/user_stats/settings.py
Labels: security

#344 309 front implement rgpd
  front/app/src/js/Cookies.js
  front/app/src/js/components/index.js
  front/app/src/js/components/notifications/Notification.js
  front/app/src/js/components/notifications/ToastNotifications.js
  front/app/src/js/components/pages/authentication/ActivateAccount.js
  front/app/src/js/components/pages/authentication/ActivateAccountContent.js
  front/app/src/js/components/pages/authentication/SignIn.js
  front/app/src/js/components/pages/authentication/SignInContent.js
  front/app/src/js/components/pages/authentication/SignUp.js
  front/app/src/js/components/pages/authentication/SignUpContent.js
  front/app/src/js/components/pages/authentication/TwoFactorAuth.js
  front/app/src/js/components/pages/authentication/index.js
  front/app/src/js/components/pages/index.js
  front/app/src/js/components/pages/privacy_policy/PrivacyPolicy.js
  front/app/src/js/components/pages/privacy_policy/PrivacyPolicyContent.js
  front/app/src/js/components/pages/privacy_policy/index.js
  front/app/src/js/components/pages/reset_password/ResetPassword.js
  front/app/src/js/components/pages/reset_password/ResetPasswordCode.js
  front/app/src/js/components/pages/reset_password/ResetPasswordEmail.js
  front/app/src/js/components/pages/reset_password/ResetPasswordNew.js
  front/app/src/js/components/pages/tournaments/TournamentCreate.js
  front/app/src/js/components/pages/tournaments/TournamentCreateContent.js
  front/app/src/js/components/utilities/Error.js
  front/app/src/js/components/utilities/ErrorContent.js
  front/app/src/js/components/utilities/index.js
  front/app/src/js/main.js
  front/app/src/js/utils/api/BaseClient.js
Labels: enhancement

#350 Increase healthchecks retries
  pong_server/docker/docker-compose.yaml
  tournament/docker/docker-compose.yaml
  user_management/docker/docker-compose.yaml
  user_stats/docker/docker-compose.yaml
Labels: refactoring

#349 Add healthcheck for notification
  front/docker/docker-compose.yaml
  notification/docker/docker-compose.yaml
  notification/src/notification/urls.py
  notification/src/notification/views.py
Labels: security

#345 Crontab - Delete inactive tournaments
  common/src/settings.py
  crontab/Dockerfile
  crontab/config/cronjob
  crontab/docker-compose.yaml
  crontab/requirements.txt
  crontab/script/delete_inactive_tournament.py
  docker-compose.yaml
  front/docker/docker-compose.yaml
  tournament/doc/tournament-api-documentation.md
  tournament/src/api/migrations/0016_tournament_start_datetime.py
  tournament/src/api/models.py
  tournament/src/api/urls.py
  tournament/src/api/views/delete_inactive_tournament.py
  tournament/src/api/views/manage_tournament_views.py
Labels: enhancement

#368 366 refactor tournament
  front/app/src/js/components/pages/tournaments/TournamentCreateContent.js
  front/app/src/js/components/pages/tournaments/Tournaments.js
  front/app/src/js/components/pages/tournaments/TournamentsContent.js
  front/app/src/js/components/pages/tournaments/TournamentsList.js
  front/app/src/js/components/pages/user_profile/UserProfileMatchList.js
  front/app/src/js/main.js
Labels: bug, enhancement

#360 264 oauth2 get the id of the third app
  user_management/src/user/migrations/0003_user_id_from_auth_service_alter_user_oauth.py
  user_management/src/user/migrations/0004_rename_id_from_auth_service_user_id_from_42api_and_more.py
  user_management/src/user/migrations/0005_remove_user_oauth_user_oauth_42api_user_oauth_github.py
  user_management/src/user/migrations/0006_alter_user_options_useroauth.py
  user_management/src/user/migrations/0007_remove_user_id_from_42api_remove_user_id_from_github_and_more.py
  user_management/src/user/migrations/0008_alter_useroauth_user.py
  user_management/src/user/models.py
  user_management/src/user/views/delete_account.py
  user_management/src/user/views/oauth.py
  user_management/src/user/views/send_user_infos.py
  user_management/src/user_management/settings.py
Labels: enhancement

#367 275 ranking page
  front/app/src/js/components/index.js
  front/app/src/js/components/navbar/ConnectedNavbar.js
  front/app/src/js/components/pages/index.js
  front/app/src/js/components/pages/ranking/Ranking.js
  front/app/src/js/components/pages/ranking/RankingContent.js
  front/app/src/js/components/pages/ranking/index.js
  front/app/src/js/components/pages/user_profile/UserProfileMatchList.js
  front/app/src/js/main.js
  front/app/src/js/utils/api/UserStatsClient.js
Labels: enhancement

#373 move depends-on in global docker-compose
  crontab/docker-compose.yaml
  docker-compose.yaml
  front/docker/docker-compose.yaml
  notification/docker/docker-compose.yaml
  pong_server/docker/docker-compose.yaml
  tournament/docker/docker-compose.yaml
  user_management/docker/docker-compose.yaml
  user_stats/docker/docker-compose.yaml
Labels: bug

#374 326 fix browser issues warning
  front/app/src/js/components/pages/authentication/SignUpContent.js
  front/app/src/js/components/pages/reset_password/ResetPasswordEmail.js
  front/app/src/js/components/pages/settings/SettingsContent.js
  front/app/src/js/components/pages/tournaments/TournamentCreateContent.js
Labels: enhancement

#381 376-verify-auth-in-game-page
  front/app/src/js/components/game/game.js
  front/app/src/js/main.js
Labels: security

#385 Game rework
  front/app/package.json
  front/app/public/assets/models/board.glb
  front/app/public/assets/models/wall.glb
  front/app/src/js/components/game/Engine/_GameSocketIO.js
  front/app/src/js/components/game/Engine/_ThreeJS.js
  front/app/src/js/components/game/Scene/Ball.js
  front/app/src/js/components/game/Scene/Match.js
  front/app/src/js/components/game/Scene/Player/Paddle.js
  front/app/src/js/components/game/Scene/Player/Player.js
  front/app/src/js/components/game/Scene/Player/_Board.js
  front/app/src/js/components/game/Scene/Scene.js
  front/app/src/js/components/game/game.js
  pong_server/src/game_server/settings.py
Labels: refactoring

#387 352 auto redirect player in game
  front/app/src/js/components/pages/home/HomeContent.js
  front/app/src/js/components/pages/tournaments/TournamentsContent.js
  front/app/src/js/utils/api/PongServerClient.js
  front/app/src/js/utils/api/index.js
  pong_server/src/game_creator/api/urls.py
Labels: enhancement

#390 378 implement game end page
  front/app/src/js/components/game/Engine/_GameSocketIO.js
  front/app/src/js/components/game/Engine/_ThreeJS.js
  front/app/src/js/components/game/Scene/Player/Player.js
  front/app/src/js/components/game/Scene/Player/_Board.js
  front/app/src/js/components/game/Scene/PlayerLocation.js
  front/app/src/js/components/game/Scene/Scene.js
  front/app/src/js/components/game/game.js
  pong_server/src/game_server/Game/GameManager.py
Labels: enhancement

#394 Await newPlayer.init()
  front/app/src/js/components/game/Scene/Match.js
Labels: bug

#388 Fix switch dark/light mode in game
  front/app/src/js/components/game/game.js
Labels: bug

#398 346 flush old pending accounts
  crontab/config/cronjob
  crontab/script/delete_inactive_users.py
  user_management/docker/requirements.txt
  user_management/src/commands/cron_delete_inactive_users.py
  user_management/src/user/migrations/0001_initial.py
  user_management/src/user/migrations/0002_user_oauth.py
  user_management/src/user/migrations/0003_user_id_from_auth_service_alter_user_oauth.py
  user_management/src/user/migrations/0004_rename_id_from_auth_service_user_id_from_42api_and_more.py
  user_management/src/user/migrations/0005_remove_user_oauth_user_oauth_42api_user_oauth_github.py
  user_management/src/user/migrations/0006_alter_user_options_useroauth.py
  user_management/src/user/migrations/0007_remove_user_id_from_42api_remove_user_id_from_github_and_more.py
  user_management/src/user/migrations/0008_alter_useroauth_user.py
  user_management/src/user/migrations/__init__.py
  user_management/src/user/models.py
  user_management/src/user/tests.py
  user_management/src/user/urls.py
  user_management/src/user/views/delete_inactive_users.py
  user_management/src/user_management/settings.py
Labels: enhancement

#402 try disconnect and emit methods
  front/app/src/js/components/game/Engine/_GameSocketIO.js
Labels: bug

#421 Fix user stats graph
  user_stats/src/api/tests/test_user_graph.py
  user_stats/src/api/views/user_graph.py
Labels: bug

#422 reload page after logout
  front/app/src/js/utils/api/BaseClient.js
Labels: bug

#423 decrement friends count in user-stats on account deletion
  user_management/src/user/views/delete_account.py
  user_management/src/user/views/friends.py
  user_management/src/user_management/utils.py
Labels: bug

#424 Add arrows and upper key to move around in games
  front/app/src/js/components/game/Engine/_KeyHookHandler.js
Labels: enhancement

#425 secure tooltip callback and around win rate
  front/app/src/js/components/pages/user_profile/UserProfileChartsCards.js
Labels: bug

#431 fix alphanumeric in inputValidator
  front/app/src/js/utils/InputValidator.js
Labels: bug

#426 add button type in settings form
  front/app/src/js/components/pages/settings/SettingsContent.js
Labels: bug

#429 Deleting errors as objects
  user_management/src/user/views/update_infos.py
Labels: bug

#432 Fix user stats graph 2
  front/app/src/js/components/pages/user_profile/UserProfileContent.js
  user_stats/src/api/tests/test_user_graph.py
  user_stats/src/api/views/user_graph.py
Labels: bug

#434 Loading screen rework
  front/app/src/js/components/game/Engine/_ThreeJS.js
  front/app/src/js/components/game/Scene/LoadingScreenScene.js
  front/app/src/js/components/game/Scene/Scene.js
  front/app/src/js/components/game/Scene/SceneSky.js
Labels: enhancement

#435 fix matchmaking error when player is already in game
  front/app/src/js/components/buttons/MultiplayerButton.js
  matchmaking/src/error_message.py
  matchmaking/src/matchmaking.py
Labels: bug

#437 add service authentication in `statistics/match/`
  user_stats/src/api/tests/test_match.py
  user_stats/src/api/tests/test_user.py
  user_stats/src/api/tests/test_user_graph.py
  user_stats/src/api/tests/test_user_history.py
  user_stats/src/api/tests/test_user_progress.py
  user_stats/src/api/views/match.py
Labels: security

#438 Optimize game
  front/app/public/assets/models/wall.glb
  front/app/src/js/components/game/Engine/_ThreeJS.js
  front/app/src/js/components/game/Scene/Ball.js
  front/app/src/js/components/game/Scene/Player/Paddle.js
  front/app/src/js/components/game/Scene/Player/_Board.js
Labels: refactoring

#456 Add tournament endpoints
  tournament/doc/tournament-api-documentation.md
  tournament/src/api/migrations/0017_alter_match_player_1_alter_match_player_2_and_more.py
  tournament/src/api/models.py
  tournament/src/api/tests/test_tournament_players.py
  tournament/src/api/urls.py
  tournament/src/api/views/tournament_players_views.py
Labels: enhancement

#458 Optimize game when running on low-end devices
  front/app/src/js/components/game/Engine/_ThreeJS.js
  front/app/src/js/components/game/Scene/Player/Paddle.js
  front/app/src/js/components/game/Scene/Player/_Board.js
  front/app/src/js/components/game/Scene/Scene.js
Labels: enhancement

#460 Handle 409 status_code in start tournament
  tournament/src/api/tests/test_tournament.py
  tournament/src/api/views/manage_tournament_views.py
Labels: bug

#461 Tournaments can now be played with 2 players
  tournament/src/tournament/settings.py
Labels: refactoring

#463 407 fix tournament cards
  front/app/src/js/components/game/Engine/_GameSocketIO.js
  front/app/src/js/components/game/Scene/Scene.js
  front/app/src/js/components/game/game.js
  pong_server/src/game_server/settings.py
  tournament/src/api/views/manage_tournament_views.py
Labels: bug, enhancement

#468 Removes the ball at the end of a match
  front/app/src/js/components/game/Engine/_GameSocketIO.js
  front/app/src/js/components/game/Scene/Ball.js
  front/app/src/js/components/game/Scene/Scene.js
Labels: enhancement

#480 Clean up threeJS scene
  front/app/src/js/components/game/Engine/Engine.js
  front/app/src/js/components/game/Engine/_ThreeJS.js
Labels: enhancement

#481 Use InternalRequests to get elo in generate_matches_views.py
  tournament/src/api/views/generate_matches_views.py
Labels: bug, security

#486 Update tournament Documentation.md
  doc/Documentation.md
Labels: documentation

#509 fix front avatar format
  front/app/src/js/components/pages/settings/SettingsContent.js
Labels: bug

#508 fix alert color
  front/app/src/js/components/pages/settings/SettingsContent.js
Labels: bug

#507 display finished and private tournaments by default
  front/app/src/js/components/pages/tournaments/TournamentsList.js
Labels: enhancement

#506 fix tournament min player
  front/app/src/js/components/pages/tournaments/TournamentCreateContent.js
Labels: bug

#514 fix tournament list
  front/app/src/js/components/pages/tournaments/TournamentsContent.js
Labels: bug

#515 change to large error message
  front/app/src/js/components/pages/settings/SettingsContent.js
  user_management/src/user/views/avatar.py
Labels: enhancement

#513 fix home responsiveness
  front/app/src/js/components/layouts/FriendsSidebar.js
  front/app/src/js/components/pages/home/HomeContent.js
Labels: bug

#530 Create the user in user_stats only when the account is verified
  user_management/src/user/test_friends.py
  user_management/src/user/tests.py
  user_management/src/user/views/sign_up.py
  user_management/src/user/views/verify_email.py
Labels: bug
