Repository tdameros/42-transcendence, pull requests merged in 2024-02, with the labels that each got.

#152 fix PLAYERS_NOT_INT error message
  tournament/src/api/error_message.py
Labels: bug

#172 Fix user management user endpoint in tournament
  common/src/settings.py
  tournament/src/api/tests/test_self_ongoing.py
  tournament/src/api/tests/test_tournament.py
  tournament/src/api/views/self_ongoing_tournament.py
  tournament/src/api/views/tournament_utils.py
  tournament/src/api/views/tournament_views.py
  tournament/src/tournament/settings.py
Labels: bug

#224 fix health check
  pong_server/docker/docker-compose.yaml
  tournament/docker/docker-compose.yaml
  user_management/docker/docker-compose.yaml
  user_stats/docker/docker-compose.yaml
Labels: bug

#225 Increment players counter when you join a tournament
  front/app/src/js/components/pages/tournaments/TournamentDetails.js
  front/app/src/js/components/pages/tournaments/Tournaments.js
Labels: bug

#221 Service authentication
  .github/workflows/matchmaking.yaml
  .github/workflows/tournament.yaml
  .github/workflows/user_management.yaml
  .github/workflows/user_stats.yaml
  Makefile
  common/docker/requirements.txt
  common/src/generate_env.py
  common/src/jwt_managers.py
  common/src/settings.py
  matchmaking/docker/docker-compose.yaml
  tournament/docker/docker-compose.yaml
  user_management/docker/docker-compose.yaml
  user_management/src/user/views/sign_up.py
  user_stats/docker/docker-compose.yaml
  user_stats/src/api/tests/test_user.py
  user_stats/src/api/views/user.py
Labels: security

#230 Fix crash when client sends wrong jwt
  front/app/src/js/components/Notification.js
  notification/src/api/consumers.py
Labels: bug

#210 Profile picture2
  doc/Documentation.md
  user_management/doc/User_management.md
  user_management/src/user/static/default_avatar.png
  user_management/src/user/test_resources/avatar.png
  user_management/src/user/test_resources/default_avatar.png
  user_management/src/user/test_resources/too_big_avatar.png
  user_management/src/user/tests.py
  user_management/src/user/urls.py
  user_management/src/user/views/avatar.py
  user_management/src/user/views/update_infos.py
  user_management/src/user_management/settings.py
  user_management/src/user_management/utils.py
Labels: enhancement

#217 Fix authorization headers
  user_management/doc/User_management.md
  user_management/src/user/tests.py
  user_management/src/user/views/search_username.py
  user_management/src/user/views/update_infos.py
  user_management/src/user/views/user_id.py
  user_management/src/user/views/username.py
Labels: security

#236 Delete user
  common/src/settings.py
  doc/Documentation.md
  tournament/src/api/tests/test_tournament_players.py
  tournament/src/api/views/tournament_players_views.py
  user_management/doc/User_management.md
  user_management/src/user/models.py
  user_management/src/user/tests.py
  user_management/src/user/urls.py
  user_management/src/user/views/delete_account.py
  user_management/src/user/views/refresh_JWT.py
  user_management/src/user_management/settings.py
Labels: enhancement

#240 fix service token generation
  common/src/internal_requests.py
Labels: bug

#247 Refactor friends
  doc/Documentation.md
  front/app/src/js/components/navbar/NotificationNav.js
  front/app/src/js/utils/api/UserManagementClient.js
  user_management/doc/User_management.md
  user_management/src/user/test_friends.py
  user_management/src/user/tests.py
  user_management/src/user/urls.py
  user_management/src/user/views/friends.py
Labels: enhancement, refactoring

#248 matchmaking ssl
  common/src/settings.py
  front/app/src/js/components/pages/Multiplayer.js
  matchmaking/docker/docker-compose.yaml
  matchmaking/src/server.py
Labels: security

#251 fix user-stats friends update
  common/src/internal_requests.py
  user_management/src/user/migrations/0011_user_account_deleted_alter_pendingoauth_hashed_state.py
  user_management/src/user/test_friends.py
  user_management/src/user/views/friends.py
Labels: bug

#255 Send new friend status
  common/src/settings.py
  notification/doc/notification-api-documentation.md
  notification/src/api/consumers.py
  notification/src/api/error_message.py
  notification/src/api/urls.py
  notification/src/api/views/new_friend.py
  notification/src/api/views/notification.py
  notification/src/notification/settings.py
  user_management/src/user/test_friends.py
  user_management/src/user/views/friends.py
Labels: enhancement

#254 fix non tried internal request
  user_management/src/user/views/friends.py
Labels: security

#256 Pong server now communicates with user-stats and tournament
  .github/workflows/pong-server.yaml
  common/src/jwt_managers.py
  front/app/src/js/components/game/Engine/_GameSocketIO.js
  front/doc/pong.md
  pong_server/.gitignore
  pong_server/dev_game_server.sh
  pong_server/docker/docker-compose.yaml
  pong_server/docker/run.sh
  pong_server/src/game_creator/api/GameCreator.py
  pong_server/src/game_creator/api/views.py
  pong_server/src/game_server/EventEmitter.py
  pong_server/src/game_server/Game/GameManager.py
  pong_server/src/game_server/Game/Match.py
  pong_server/src/game_server/PostSender/PostSender.py
  pong_server/src/game_server/PostSender/_ABaseAPI.py
  pong_server/src/game_server/PostSender/_DevAPI.py
  pong_server/src/game_server/PostSender/_TournamentAPI.py
  pong_server/src/game_server/PostSender/_UserStatsAPI.py
  pong_server/src/game_server/PostSender/__init__.py
  pong_server/src/game_server/main.py
  pong_server/src/shared_code/settings.py
Labels: enhancement

#262 Fix 500 error when a user accepts a friend request
  notification/src/api/views/friend_notification.py
Labels: bug

#252 hash pass with make_password
  user_management/src/user/tests.py
  user_management/src/user/views/sign_in.py
  user_management/src/user/views/sign_up.py
  user_management/src/user_management/settings.py
Labels: security

#269 Fix notification on user disconnection
  notification/src/api/consumers.py
Labels: bug, invalid

#270 Add service authentication for updating tournament matches
  notification/src/notification/settings.py
  tournament/src/api/tests/test_tournament_matches.py
  tournament/src/api/views/manage_match_views.py
Labels: security

#297 Delete the ssl container in make down and clean
  Makefile
Labels: enhancement

#296 Added the possibility of logging in with a username or email address
  front/app/src/js/components/pages/authentication/SignIn.js
  front/app/src/js/components/pages/authentication/TwoFactorAuth.js
  front/app/src/js/utils/api/UserManagementClient.js
  user_management/doc/User_management.md
  user_management/src/user/tests.py
  user_management/src/user/views/sign_in.py
Labels: enhancement

#300 257 implement toast error
  front/app/src/js/components/buttons/IntraButton.js
  front/app/src/js/components/game/Engine/_GameSocketIO.js
  front/app/src/js/components/layouts/Friends.js
  front/app/src/js/components/navbar/ConnectedNavbar.js
  front/app/src/js/components/navbar/Navbar.js
  front/app/src/js/components/navbar/NotificationNav.js
  front/app/src/js/components/navbar/SearchNav.js
  front/app/src/js/components/notifications/Notification.js
  front/app/src/js/components/notifications/ToastNotifications.js
  front/app/src/js/components/pages/authentication/SignIn.js
  front/app/src/js/components/pages/local/Local.js
  front/app/src/js/components/pages/multiplayer/Multiplayer.js
  front/app/src/js/components/pages/tournaments/TournamentDetails.js
  front/app/src/js/components/pages/tournaments/TournamentsContent.js
  front/app/src/js/components/pages/user_profile/UserProfile.js
  front/app/src/js/components/pages/user_profile/UserProfileContent.js
  front/app/src/js/components/pages/user_profile/UserProfileHeader.js
  front/app/src/js/components/pages/user_profile/UserProfileMatchList.js
  front/app/src/js/utils/api/BaseClient.js
Labels: bug, enhancement

#298 Fix friends progress
  common/src/settings.py
  doc/Documentation.md
  user_management/src/user/test_friends.py
  user_management/src/user/views/friends.py
  user_stats/doc/user-stats-documentation.md
  user_stats/src/api/error_message.py
  user_stats/src/api/migrations/0007_remove_match_user_friends_friendshistory.py
  user_stats/src/api/models.py
  user_stats/src/api/tests/test_friends.py
  user_stats/src/api/tests/test_user_progress.py
  user_stats/src/api/urls.py
  user_stats/src/api/views/match.py
  user_stats/src/api/views/user_friends.py
  user_stats/src/api/views/user_progress.py
Labels: bug, refactoring

#301 Implement private match
  common/docker/requirements.txt
  notification/src/notification/settings.py
  pong_server/doc/game_creator.md
  pong_server/src/game_creator/api/error_messages.py
  pong_server/src/game_creator/api/urls.py
  pong_server/src/game_creator/api/views.py
  pong_server/src/game_server/PostSender/PostSender.py
  pong_server/src/game_server/PostSender/_PrivateGameAPI.py
  pong_server/src/shared_code/settings.py
Labels: enhancement

#305 only accept 2fa when the user first tries to verify a code
  user_management/src/user/views/two_fa.py
Labels: enhancement

#307 Add friend endpoint
  common/src/settings.py
  pong_server/src/game_creator/api/error_messages.py
  pong_server/src/game_creator/api/views.py
  user_management/doc/User_management.md
  user_management/src/user/error_messages.py
  user_management/src/user/test_friends.py
  user_management/src/user/urls.py
  user_management/src/user/views/friends.py
Labels: enhancement

#311 Ranking
  doc/Documentation.md
  user_stats/doc/user-stats-documentation.md
  user_stats/src/api/tests/test_ranking.py
  user_stats/src/api/urls.py
  user_stats/src/api/views/ranking.py
  user_stats/src/user_stats/settings.py
Labels: enhancement

#319 update avatar and verify email doc
  user_management/doc/User_management.md
  user_management/src/user/tests.py
  user_management/src/user/urls.py
  user_management/src/user/views/avatar.py
Labels: documentation, enhancement

#316 Update delete_ssl_container rule in Makefile
  Makefile
Labels: refactoring

#334 Put the access_token in the request body to anonymize a tournament player
  tournament/doc/tournament-api-documentation.md
  tournament/src/api/error_message.py
  tournament/src/api/tests/test_tournament_players.py
  tournament/src/api/views/tournament_players_views.py
  user_management/src/user/views/delete_account.py
Labels: bug
